### ISSUE TITLE
utils might shadow rdoc, if loaded later

### ISSUE THREAD

**Issue by gaborcsardi** [mdequeljoe/rdoc#1]
Not sure what to do about this, maybe rdoc could depend on utils, but maybe you could just document it in the README? 

I.e. to make sure rdoc is used I have this in the profile:

```r
library(utils)
rdoc::use_rdoc()
```

**Comment by jimhester** [comment]
I was just going to open this exact thing (and remedy) myself. 😁

**Comment by jimhester** [comment]
I guess one easy workaround is to put `library(utils)` inside `use_rdoc()`, then this would just happen automatically.

**Comment by mdequeljoe** [comment]
oh right! i noticed that too when i first put that in my .Rprofile so i set it like this:

```r
if (isatty(stdout())) {
  .First.sys()
  rdoc::use_rdoc()
}
```
and i agree - this should be mentioned in the README
thanks!

**Comment by mdequeljoe** [comment]
also i like the suggested workaround, in the end this is probably more convenient
