### ISSUE TITLE
Does not work with namespace::

### ISSUE THREAD

**Issue by rubak** [mdequeljoe/rdoc#6]
In a fresh R session:

```
> rdoc::rdoc(MASS::bcv)
Error in dirname(path) : a character vector argument expected
```

It works nicely once the package is loaded:
```
> library(MASS)
> rdoc::rdoc(bcv)
```

**Comment by mdequeljoe** [comment]
thanks for noting this. This is coming from `utils::help` which `rdoc` uses:

```r
utils::help(MASS::bcv)
#> Error in utils::help(MASS::bcv) : 
#>  'topic' should be a name, length-one character vector or reserved word
```
I think it would be helpful if this same error message is returned when used via `rdoc` instead of the current one

**Comment by rubak** [comment]
I didn't even realize this. I never use `help` but rather `?` which works with namespace:: and I assumed the same was the case with `help`. Using `?` also works as expected in `rdoc` when you use `use_rdoc()` and then call `?`:

``` r
library(rdoc)
use_rdoc()
?MASS::bcv
```

I find it strange that `help` doesn't work like this, but you are following base R behavior and that might be the best practice here, so you can go ahead and close the issue as you like. Thanks for looking into it anyway.

**Comment by mdequeljoe** [comment]
yeh on second thought i think allowing for a minor deviation from `help` could make sense, since the following works:
```r
help(bcv, MASS)
```

so it could be checked within `rdoc` if topics are passed with the double colon operator and then re-arranged accordingly
